packages:
  - 'apps/web'
  - 'apps/api'
  - 'packages/*'

allowBuilds:
  '@swc/core': true
  unrs-resolver: true
  esbuild: true
  sharp: true

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.7'
  - '@turbo/darwin-arm64@2.11.7'
  - '@turbo/linux-64@2.11.7'
  - '@turbo/linux-arm64@2.11.7'
  - '@turbo/windows-64@2.11.7'
  - '@turbo/windows-arm64@2.11.7'
  - turbo@2.11.7
